project:
  type: book

book:
  title: "Computational Analysis of Communication"
  author: "Wouter van Atteveldt, Damian Trilling & Carlos Arcila"
  date: "2022-03-11"
  favicon: img/favicon.png
  chapters:
    - index.qmd
    - content/chapter01.qmd
    - content/chapter02.qmd
    - content/chapter03.qmd
    - content/chapter04.qmd
    - content/chapter05.qmd
    - content/chapter06.qmd
    - content/chapter07.qmd
    - content/chapter08.qmd
    - content/chapter09.qmd
    - content/chapter10.qmd
    - content/chapter11.qmd
    - content/chapter12.qmd
    - content/chapter13.qmd
    - content/chapter14.qmd
    - content/chapter15.qmd
    - content/chapter16.qmd
    - content/references.qmd

bibliography: content/references.bib

format:
  html:
    theme: cosmo

editor: visual

engine: knitr
execute:
  warning: false
  freeze: auto