project:
  type: book

book:
  title: "Computational Analysis of Communication"
  author: "Wouter van Atteveldt, Damian Trilling & Carlos Arcila"
  date: "2022-03-11"
  chapters:
    - index.qmd
    - chapter01.qmd
    - chapter02.qmd
    - chapter03.qmd
    - chapter04.qmd
    - chapter05.qmd
    - chapter06.qmd
    - chapter07.qmd
    - chapter08.qmd
    - chapter09.qmd
    - chapter10.qmd
    - chapter11.qmd
    - chapter12.qmd
    - chapter13.qmd
    - chapter14.qmd
    - chapter15.qmd
    - chapter16.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo

editor: visual

engine: knitr
execute:
  warning: false
  freeze: auto